-- VIBES Dance — Supabase schema for conversion events
--
-- Run this in Supabase Dashboard → SQL Editor → New Query.
-- Creates the table + indexes + RLS policies for the admin dashboard.
--

-- 1. Table --------------------------------------------------------------------
create table if not exists public.conversion_events (
  id           bigint generated by default as identity primary key,
  type         text not null,                       -- button_click | widget_click
  channel      text,                                -- vk | telegram | phone | null
  context      text,                                -- hero | navbar | schedule | ...
  device       text,                                -- "📱 iPhone" | "📱 Android" | "💻 Десктоп"
  client_time  text,                                -- formatted time from the client
  created_at   timestamptz not null default now()
);

-- 2. Indexes for the dashboard aggregations ----------------------------------
create index if not exists conversion_events_type_idx     on public.conversion_events (type);
create index if not exists conversion_events_channel_idx  on public.conversion_events (channel);
create index if not exists conversion_events_context_idx  on public.conversion_events (context);
create index if not exists conversion_events_created_idx   on public.conversion_events (created_at desc);

-- 3. Row Level Security -------------------------------------------------------
-- We use the service_role key (server-side only), which bypasses RLS.
-- For safety, RLS is ENABLED but only the service role can read/write.
alter table public.conversion_events enable row level security;

-- Allow the service_role (server) to do everything.
-- (No policies for anon/authenticated — the dashboard reads via the
--  server endpoint /api/stats which uses the service_role key.)
drop policy if exists "service role can do everything" on public.conversion_events;
create policy "service role can do everything"
  on public.conversion_events
  for all
  to service_role
  using (true)
  with check (true);

-- 4. Done ---------------------------------------------------------------------
-- Verify with:
--   select count(*) from public.conversion_events;

-- 5. Allow anon (publishable key) to insert + select ------------------------
-- Needed because we use the publishable key, not service_role.
DROP POLICY IF EXISTS "anon can insert" ON public.conversion_events;
CREATE POLICY "anon can insert"
  ON public.conversion_events
  FOR INSERT TO anon
  WITH CHECK (true);

DROP POLICY IF EXISTS "anon can select" ON public.conversion_events;
CREATE POLICY "anon can select"
  ON public.conversion_events
  FOR SELECT TO anon
  USING (true);

-- 6. Allow anon (publishable key) to delete rows -----------------------------
-- Used by the admin dashboard "Reset stats" button.
DROP POLICY IF EXISTS "anon can delete" ON public.conversion_events;
CREATE POLICY "anon can delete"
  ON public.conversion_events
  FOR DELETE TO anon
  USING (true);
